### ISSUE TITLE
使用外部tomcat启动时，未成功

### ISSUE THREAD

**Issue by wangay** [wanggang1987/whoknows#1]
1 pom中改成war，删掉内置tomcat的引用；
2 WhoknowsApplication extends SpringBootServletInitializer 复写了confure方法；
3 新建了一个类：

@Configuration
@EnableScheduling
public class SpringMvcConfig extends WebMvcConfigurerAdapter {

    //setting View resolver
    @Bean
    public ViewResolver getViewResolver() {
        InternalResourceViewResolver resolver = new InternalResourceViewResolver();
        resolver.setViewClass(JstlView.class);
        resolver.setPrefix("/");
        resolver.setSuffix(".jsp");
        return resolver;
    }

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("/app/**").addResourceLocations("/app/");
        registry.addResourceHandler("/images/**").addResourceLocations("/images/");
        registry.addResourceHandler("/styles/**").addResourceLocations("/styles/");
        registry.addResourceHandler("/fonts/**").addResourceLocations("/fonts/");
        registry.addResourceHandler("/components/**").addResourceLocations("/components/");
        registry.addResourceHandler("/bower_components/**").addResourceLocations("/bower_components/");
        super.addResourceHandlers(registry);
    }

}

未成功

**Comment by moheqionglin** [comment]
你是想把 springboot 程序转成 传统的spring MVC 程序然后 自己部署到 tomcat上吗？

**Comment by wangay** [comment]
之前是那么想的，后来不打算那么做了
现在打成了jar。

话说回来，最新代码用maven打成jar是无法使用的，还需要改pom把webapp的东西打进去。

**Comment by moheqionglin** [comment]
你好，带有 前端模板引擎，同时模板引擎使用的jsp的话，spring boot比较推荐打成 war包。 除非你不用tomcat作为 内置的spring boot容器。 有任何疑问可以问我们

**Comment by moheqionglin** [comment]
如果只是想使用 springboot 作为一个REST 服务器的话， 不涉及任何 前端展示和模板解析（比如JSP, velocity等）可以直接打包成jar包。

**Comment by wangay** [comment]
好的
