### ISSUE TITLE
新增tag,后台都没有是吗

### ISSUE THREAD

**Issue by wangay** [wanggang1987/whoknows#2]
我没有找到

**Comment by wanggang1987** [comment]
确实没有UI，可以通过直接插入数据库，或者rest接口

**Comment by wangay** [comment]
ok

**Comment by wangay** [comment]
问下，这个/login是哪个地方去处理的？
没找到

$http.post('/login', $scope.loginInfo).success(function (data) {
   $log.debug('Got the following response.');
   $scope.loggingIn = true;
   LocalStorageService.put("userName", data.username, true);
   LocalStorageService.put("userId", data.id, true);
   UserService.initialize(true).then(function () {
      $scope.loggingError = false;
      $rootScope.$broadcast('event:login:success');
   });

}).

**Comment by moheqionglin** [comment]
你好，项目登录和鉴权功能采用的是 spring security（https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/）。
理解完 spring security以后， 处理登录功能的代码在：
如下这个类里面
public class AuthFilter extends AbstractAuthenticationProcessingFilter {

	private final Logger log = LoggerFactory.getLogger(this.getClass());

	private static final String DEFAULT_PROCESSING_URL = "/login";

有任何疑问可以问我们。

**Comment by wangay** [comment]
ok
